/* ============================================================
   TESTI DELL'INTERFACCIA [italiano, inglese]
   ============================================================ */
/* ============ TESTI INTERFACCIA [it,en] ============ */
const UI = {
  subtitle:["Leggi le domande, apri le porte, trova la stella!","Read the questions, open the doors, find the star!"],
  howto:["💻 Frecce o WASD · 📱 Joystick sullo schermo","💻 Arrows or WASD · 📱 On-screen joystick"],
  level:["Livello","Level"],
  readme:["🔊 Leggimi la domanda","🔊 Read the question to me"],
  reading:["🔊 Sto leggendo...","🔊 Reading..."],
  back:["torna indietro","go back"],
  praise:[["BRAVISSIMO! 🎉","SUPER! ⭐","CHE CAMPIONE! 🏅","PERFETTO! 🌟","GRANDE {NAME}! 💪"],
          ["AMAZING! 🎉","SUPER! ⭐","WHAT A CHAMPION! 🏅","PERFECT! 🌟","GREAT JOB {NAME}! 💪"]],
  wrong:["Ops! Leggi bene e prova ancora 💪","Oops! Read carefully and try again 💪"],
  bravo:["BRAVO {NAME}!","WELL DONE {NAME}!"],
  finished:["HAI FINITO TUTTO IL GIOCO!","YOU FINISHED THE WHOLE GAME!"],
  champion:["Sei un vero campione di lettura! 🌟","You are a true reading champion! 🌟"],
  completedLvl:["Hai completato il livello","You completed the level"],
  next:["Prossimo livello ➡️","Next level ➡️"],
  menuBtn:["Torna al menu 🔄","Back to menu 🔄"],
  hintKeys:["Usa le frecce ⬆️⬇️⬅️➡️ per muoverti!","Use the arrows ⬆️⬇️⬅️➡️ to move!"],
  hintJoy:["Usa il joystick per muoverti! 🕹️","Use the joystick to move! 🕹️"],
  diffE:["⭐ Facile","⭐ Easy"],
  diffH:["🔥 Difficile","🔥 Hard"],
  loadingVoice:["⏳ Scarico la voce naturale (solo la prima volta)...","⏳ Downloading natural voice (first time only)..."],
  voiceReady:["🎙️ Voce naturale pronta!","🎙️ Natural voice ready!"],
  speakBravo:["Bravo {NAME}!","Well done {NAME}!"],
  tokenMsg:["🪙 Gettone magico! Ecco una nuova domanda!","🪙 Magic token! Here is a new question!"],
  tokensUsed:["Gettoni magici usati","Magic tokens used"],
  more:["🔎 Scopri di più","🔎 Learn more"],
  readExp:["🔊 Leggimi tutto −40 ⭐","🔊 Read it all −40 ⭐"],
  go:["Continua ➡️","Continue ➡️"],
  /* jolly */
  jollyRead:["🔊 Leggi per me −40 ⭐","🔊 Read to me −40 ⭐"],
  jolly5050:["🎯 Togli una risposta −20 ⭐","🎯 Remove one answer −20 ⭐"],
  jollyNoPts:["Ti servono più punti ⭐ per questo jolly!","You need more points ⭐ for this joker!"],
  /* power-up del labirinto */
  jollyFreeRead:["🔊 Leggi per me GRATIS 🎟️","🔊 Read to me FREE 🎟️"],
  jollyFree5050:["🎯 Togli una risposta GRATIS 🎟️","🎯 Remove one answer FREE 🎟️"],
  powerHeart:["❤️ Cuore recuperato!","❤️ Heart restored!"],
  powerHeartFull:["❤️ Cuori già pieni! +10 ⭐","❤️ Hearts already full! +10 ⭐"],
  powerJolly:["🎟️ Jolly gratis! Usalo quando vuoi","🎟️ Free joker! Use it any time"],
  powerShield:["🛡️ Scudo! La tua combo è protetta","🛡️ Shield! Your streak is protected"],
  shieldSaved:["🛡️ Lo scudo ha salvato la tua combo!","🛡️ The shield saved your streak!"],
  /* domanda extra */
  bonusTitle:["💎 DOMANDA EXTRA · +15 ⭐","💎 BONUS QUESTION · +15 ⭐"],
  bonusHint:["(la risposta è nascosta nel testo qui sopra!)","(the answer is hidden in the text above!)"],
  bonusRight:["💎 SUPER! Hai letto benissimo! +15 ⭐","💎 SUPER! Great reading! +15 ⭐"],
  bonusWrong:["Ops! La risposta giusta era evidenziata in verde 💚","Oops! The right answer is shown in green 💚"],
  voiceOn:["🔊 Voce: sì","🔊 Voice: on"],
  voiceOff:["🔇 Voce: no","🔇 Voice: off"],
  musicOn:["🎵 Musica: sì","🎵 Music: on"],
  musicOff:["🎵 Musica: no","🎵 Music: off"],
  arrowOn:["🧭 Freccia: sì","🧭 Arrow: on"],
  arrowOff:["🧭 Freccia: no","🧭 Arrow: off"],
  resetBtn:["🔄 Azzera progressi","🔄 Reset progress"],
  resetAsk:["Vuoi davvero ricominciare da capo? Livelli, stelle e parole andranno persi.","Do you really want to start over? Levels, stars and words will be lost."],
  /* --- nuove funzioni --- */
  readAloneHint:["📖 Leggi da solo per più punti!","📖 Read it yourself for more points!"],
  comboMsg:["🔥 SERIE x","🔥 STREAK x"],
  aloneBonus:["📖 Letto da solo! +","📖 Read alone! +"],
  albumBtn:["📖 Parole","📖 Words"],
  albumTitle:["📖 Le mie parole nuove","📖 My new words"],
  albumEmpty:["Sconfiggi i Guardiani per collezionare parole nuove!","Beat the Guardians to collect new words!"],
  albumClose:["Chiudi","Close"],
  albumCount:["parole raccolte","words collected"],
  statPoints:["punti","points"],
  statBest:["combo record","best streak"],
  statStars:["stelle","stars"],
  /* boss */
  bossName:["IL GUARDIANO","THE GUARDIAN"],
  bossIntro:["Hai raggiunto la stella! Ma il Guardiano ti sbarra la strada. Leggi bene e sconfiggilo! ⚔️","You reached the star! But the Guardian blocks your way. Read carefully and beat it! ⚔️"],
  bossStart:["⚔️ Sfida il Guardiano!","⚔️ Challenge the Guardian!"],
  bossRead:["🔊 Leggimi la frase −40 ⭐","🔊 Read it to me −40 ⭐"],
  bossHit:["Colpito! 💥","Hit! 💥"],
  bossHurt:["Ahia! Il Guardiano ti ha colpito 💢","Ouch! The Guardian hit you 💢"],
  bossTimeout:["⏰ Troppo lento! Leggi più in fretta!","⏰ Too slow! Read faster!"],
  bossNoRush:["⏰ Tempo finito, ma nessuna fretta: rispondi quando sei pronto 😊","⏰ Time's up, but no rush: answer when you're ready 😊"],
  bossTimeBonus:["bonus tempo","time bonus"],
  bossNewWord:["✨ Parola nuova:","✨ New word:"],
  bossWin:["GUARDIANO SCONFITTO!","GUARDIAN DEFEATED!"],
  bossLose:["Il Guardiano ti ha respinto! Riprova, ce la fai! 💪","The Guardian pushed you back! Try again, you can do it! 💪"],
  bossRetry:["🔁 Riprova la sfida","🔁 Try the challenge again"],
  bossFlee:["Torna al labirinto","Back to the maze"],
  starsGot:["Stelle di questo livello","Stars for this level"],
  hintReadAll:["Leggi TUTTE le risposte prima di scegliere!","Read ALL the answers before you choose!"]
};
